/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package emenu;

import DbConnection.DbConnection;
import Service.Dish_service;
import java.awt.CardLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import model.Dish;
import java.sql.ResultSet;
import javax.swing.table.TableModel;
public class mainMenu extends javax.swing.JFrame {

    /**
     * Creates new form mainMenu
     */

    DefaultTableModel AllTableModel;
    DefaultTableModel OriginTableModel;
    DefaultTableModel CategoryTableModel;
    Dish_service dish_data;
    String Ingredient_name;

    DbConnection DB = new DbConnection();
    Connection con = (Connection) DB.getConnection();
    public mainMenu() throws SQLException, ClassNotFoundException {
        
        
        this.dish_data = new Dish_service();
        initComponents();
        int column_index = 1;
        int fist_column_width = 100;
        
        
        // Table all
        this.AllTableModel = new DefaultTableModel(){
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        
        All_Table.setModel(AllTableModel);
        AllTableModel.addColumn("ID");
        AllTableModel.addColumn("Name");
        AllTableModel.addColumn("Prices");
        List<Dish> All_Dish = dish_data.getAllDish();
        for(Dish d:All_Dish){
            AllTableModel.addRow(new Object[]{d.getID(),d.getName(),d.getPrice()});
        }     
        
        // Origin create text for combo box
        String sql_origin = "SELECT * FROM origin";
        PreparedStatement pst_origin = con.prepareStatement(sql_origin);
        ResultSet rs1 = pst_origin.executeQuery();
        Origin_Search.removeAll();
        
        while (rs1.next()){
            Origin_Search.addItem(rs1.getString(2));
        }
        
        // Category create text for combo box
        String sql_category = "SELECT * FROM category";
        PreparedStatement pst_category = con.prepareStatement(sql_category);
        ResultSet rs2 = pst_category.executeQuery();
        Category_Search.removeAll();
        
        while (rs2.next()){
            Category_Search.addItem(rs2.getString(2));
        }
        
        All_Table.addMouseListener(new MouseAdapter(){
            public void mouseClicked(MouseEvent e){
                if(e.getClickCount()==2){
                    int index = All_Table.getSelectedRow();
                    //TableModel model = All_Table.getModel();
                    String name = (String)All_Table.getValueAt(index, 1);
                    int id = (int)All_Table.getValueAt(index, 0);
                    System.out.print(id);
                    Dish_detail d  = new Dish_detail(name,id); 
                    d.setVisible(true);  
                }
            }        
        });
        
        Origin_Table.addMouseListener(new MouseAdapter(){
            public void mouseClicked(MouseEvent e){
                if(e.getClickCount()==2){
                    int index = Origin_Table.getSelectedRow();
                    //TableModel model = All_Table.getModel();
                    String name = (String)Origin_Table.getValueAt(index, 1);
                    int id = (int)Origin_Table.getValueAt(index, 0);
                    Dish_detail d  = new Dish_detail(name,id); 
                    d.setVisible(true);  
                }
            }        
        });
        
        Category_Table.addMouseListener(new MouseAdapter(){
            public void mouseClicked(MouseEvent e){
                if(e.getClickCount()==2){
                    int index = Category_Table.getSelectedRow();
                    //TableModel model = All_Table.getModel();
                    String name = (String)Category_Table.getValueAt(index, 1);
                    int id = (int)Category_Table.getValueAt(index, 0);
                    Dish_detail d  = new Dish_detail(name,id); 
                    d.setVisible(true);  
                }
            }        
        });
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Origin_Search = new javax.swing.JComboBox<>();
        Main_Panel = new javax.swing.JPanel();
        All_Panel = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        All_Table = new javax.swing.JTable();
        Origin_Panel = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        Origin_Table = new javax.swing.JTable();
        Category_Panel = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        Category_Table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        Category_Search = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EMENU");
        setBackground(new java.awt.Color(255, 204, 204));

        Origin_Search.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Origin_SearchItemStateChanged(evt);
            }
        });
        Origin_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Origin_SearchActionPerformed(evt);
            }
        });

        Main_Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Main_Panel.setLayout(new java.awt.CardLayout());

        All_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        All_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                All_TableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(All_Table);

        javax.swing.GroupLayout All_PanelLayout = new javax.swing.GroupLayout(All_Panel);
        All_Panel.setLayout(All_PanelLayout);
        All_PanelLayout.setHorizontalGroup(
            All_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
        );
        All_PanelLayout.setVerticalGroup(
            All_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(All_PanelLayout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Main_Panel.add(All_Panel, "card6");

        Origin_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Origin_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Origin_TableMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(Origin_Table);

        javax.swing.GroupLayout Origin_PanelLayout = new javax.swing.GroupLayout(Origin_Panel);
        Origin_Panel.setLayout(Origin_PanelLayout);
        Origin_PanelLayout.setHorizontalGroup(
            Origin_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
        );
        Origin_PanelLayout.setVerticalGroup(
            Origin_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Origin_PanelLayout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Main_Panel.add(Origin_Panel, "card7");

        Category_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Category_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Category_TableMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(Category_Table);

        javax.swing.GroupLayout Category_PanelLayout = new javax.swing.GroupLayout(Category_Panel);
        Category_Panel.setLayout(Category_PanelLayout);
        Category_PanelLayout.setHorizontalGroup(
            Category_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
        );
        Category_PanelLayout.setVerticalGroup(
            Category_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Category_PanelLayout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        Main_Panel.add(Category_Panel, "card8");

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 0, 36)); // NOI18N
        jLabel2.setText("~ MENU ~");

        jButton5.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jButton5.setText("All");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        Category_Search.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Category_SearchItemStateChanged(evt);
            }
        });
        Category_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Category_SearchActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jButton1.setText("Category");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jButton2.setText("Origin");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Origin_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Category_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton1))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Origin_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Category_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(Main_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Origin_Search.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Origin_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Origin_SearchActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout)Main_Panel.getLayout();
        cardLayout.show(Main_Panel,"card7");
    }//GEN-LAST:event_Origin_SearchActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout)Main_Panel.getLayout();
        cardLayout.show(Main_Panel,"card6");
        Category_Search.setEnabled(false);
        Origin_Search.setEnabled(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void Origin_SearchItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Origin_SearchItemStateChanged
        // TODO add your handling code here:
        String origin_name = Origin_Search.getSelectedItem().toString();
        Dish_service dish_data_origin = new Dish_service();
        this.OriginTableModel = new DefaultTableModel(){
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        
        Origin_Table.setModel(OriginTableModel);
        OriginTableModel.addColumn("ID");
        OriginTableModel.addColumn("Name");
        OriginTableModel.addColumn("Prices");
        List<Dish> Origin_Dish = null;
        try {
            Origin_Dish = dish_data_origin.getDishByOrigin(origin_name);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(mainMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(mainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        for(Dish d:Origin_Dish){
            OriginTableModel.addRow(new Object[]{d.getID(),d.getName(),d.getPrice()});
        }
    }//GEN-LAST:event_Origin_SearchItemStateChanged

    private void Category_SearchItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Category_SearchItemStateChanged
        // TODO add your handling code here:
        String category_name = Category_Search.getSelectedItem().toString();
        Dish_service dish_data_category = new Dish_service();
        this.CategoryTableModel = new DefaultTableModel(){
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        
        Category_Table.setModel(CategoryTableModel);
        CategoryTableModel.addColumn("ID");
        CategoryTableModel.addColumn("Name");
        CategoryTableModel.addColumn("Prices");
        List<Dish> Category_Dish = null;
        try {
            Category_Dish = dish_data_category.getDishByCategory(category_name);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(mainMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(mainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        for(Dish d:Category_Dish){
            CategoryTableModel.addRow(new Object[]{d.getID(),d.getName(),d.getPrice()});
        }
    }//GEN-LAST:event_Category_SearchItemStateChanged

    private void Category_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Category_SearchActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout)Main_Panel.getLayout();
        cardLayout.show(Main_Panel,"card8");
    }//GEN-LAST:event_Category_SearchActionPerformed

    private void Category_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Category_TableMouseClicked
        // TODO add your handling code here:
        //int index = Category_Table.getSelectedRow();
        //TableModel model = Category_Table.getModel();
        //String name = model.getValueAt(index, 1).toString();
        //Dish_detail d  = new Dish_detail(name); // ingredient table        
        //d.setVisible(true);
        
    }//GEN-LAST:event_Category_TableMouseClicked

    private void All_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_All_TableMouseClicked
        // TODO add your handling code here:
        
        
        //int index = All_Table.getSelectedRow();
        //TableModel model = All_Table.getModel();
        //String name = model.getValueAt(index, 1).toString();
        //Dish_detail d  = new Dish_detail(name);        
        //d.setVisible(true);               
    }//GEN-LAST:event_All_TableMouseClicked

    private void Origin_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Origin_TableMouseClicked
        // TODO add your handling code here:
        //int index = Origin_Table.getSelectedRow();
        //TableModel model = Origin_Table.getModel();
        //String name = model.getValueAt(index, 1).toString();
        //Dish_detail d  = new Dish_detail(name);        
        //d.setVisible(true);
    }//GEN-LAST:event_Origin_TableMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Category_Search.setEnabled(false);
        Origin_Search.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Category_Search.setEnabled(true);
        Origin_Search.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new mainMenu().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(mainMenu.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(mainMenu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel All_Panel;
    private javax.swing.JTable All_Table;
    private javax.swing.JPanel Category_Panel;
    private javax.swing.JComboBox<String> Category_Search;
    private javax.swing.JTable Category_Table;
    private javax.swing.JPanel Main_Panel;
    private javax.swing.JPanel Origin_Panel;
    private javax.swing.JComboBox<String> Origin_Search;
    private javax.swing.JTable Origin_Table;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    // End of variables declaration//GEN-END:variables
}
